version: 1.13.0.{build}
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true
environment:
  lslversion: 1.13.0-b3
  LSLDIST_URL: "https://github.com/sccn/liblsl/releases/download"
  CMakeArgs: ""
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      QTCOMPILER: msvc2017_64
      QTVER: 5.11
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1604
      DEPLOYNAME: Linux64-xenial
install:
- cmd: appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip -FileName ninja.zip
- cmd: appveyor DownloadFile %LSLDIST_URL%/%lslversion%/liblsl-%lslversion%-Win64.7z -FileName liblsl_x64.7z
- cmd: 7z x ninja.zip -oC:\projects\deps\ninja > nul
- cmd: 7z x liblsl_x64.7z
- cmd: set PATH=C:\projects\deps\ninja;%PATH%
- cmd: ninja --version
- sh: set -x
- sh: wget ${LSLDIST_URL}/${lslversion}/liblsl-${lslversion}-${DEPLOYNAME}.deb -O lsl.deb
- sh: dpkg -x lsl.deb LSL
- sh: sudo apt update && sudo apt install -y qtbase5-dev
build_script:
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
- mkdir build
- cd build
- cmd: cmake -G Ninja -DQt5_DIR=C:/Qt/%QTVER%/%QTCOMPILER%/lib/cmake/Qt5 -DBOOST_ROOT=C:/Libraries/boost_1_67_0 -DLSL_INSTALL_ROOT=LSL/ %CMakeArgs% ../
- sh: cmake -DLSL_INSTALL_ROOT=LSL/usr -DLSL_UNIXFOLDERS=1 ${CMakeArgs} ..
- cmake --build . --config Release --target install
- cpack
artifacts:
- path: 'build/*.deb'
- path: 'build/*.tar.*'
- path: 'build/*.7z'
