version: 1.13.1.{build}
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true
environment:
  lsltag: 1.13.1
  lslversion: 1.13.1
  LSLDIST_URL: "https://github.com/sccn/liblsl/releases/download"
  CMakeArgs: ""
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    QTCOMPILER: msvc2017_64
    QTVER: 5.13.2
#  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804  # Now handled by GitHub Actions
#    DEPLOYNAME: Linux64-bionic
install:
- cmd: appveyor DownloadFile %LSLDIST_URL%/%lsltag%/liblsl-%lslversion%-Win64.zip -FileName liblsl_x64.zip
- cmd: 7z x liblsl_x64.zip -oLSL
- sh: wget ${LSLDIST_URL}/${lsltag}/liblsl-${lslversion}-${DEPLOYNAME}.deb -O lsl.deb
- sh: sudo dpkg -i lsl.deb
- sh: sudo apt update && sudo apt install -y qtbase5-dev
build_script:
- cmd: cmake -S . -B build -DQt5_DIR=C:/Qt/%QTVER%/%QTCOMPILER%/lib/cmake/Qt5 -DLSL_INSTALL_ROOT=LSL/ %CMakeArgs% -A x64
- sh: cmake -S . -B build -DLSL_UNIXFOLDERS=1 -DCPACK_DEBIAN_PACKAGE_SHLIBDEPS=1 ${CMakeArgs}
- cmake --build build --config Release -j --target package
artifacts:
- path: 'build/*.deb'
- path: 'build/*.tar.*'
- path: 'build/*.7z'
- path: 'build/*.zip'
deploy:
  provider: GitHub
  auth_token:
    secure: XzGnVTRjZI2AuQzR5A6qPgZViAAbBVq7/VhM7O8kyTmjIkvUjH1RrwWiFLuinsus
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true
