version: 1.13.0.{build}
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true
environment:
  lsltag: 1.13.0-b13
  lslversion: 1.13.0
  LSLDIST_URL: "https://github.com/sccn/liblsl/releases/download"
  CMakeArgs: ""
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      QTCOMPILER: msvc2017_64
      QTVER: 5.13
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      DEPLOYNAME: Linux64-bionic
install:
- cmd: appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip -FileName ninja.zip
- cmd: appveyor DownloadFile %LSLDIST_URL%/%lsltag%/liblsl-%lslversion%-Win64.7z -FileName liblsl_x64.7z
- cmd: 7z x ninja.zip
- cmd: set PATH=%cd%;%PATH%
- cmd: 7z x liblsl_x64.7z -oLSL
- cmd: ninja --version
- sh: set -x
- sh: wget ${LSLDIST_URL}/${lsltag}/liblsl-${lslversion}-${DEPLOYNAME}.deb -O lsl.deb
- sh: dpkg -x lsl.deb LSL
- sh: sudo apt update && sudo apt install -y qtbase5-dev
build_script:
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
- cmd: cmake -S . -B build -G Ninja -DQt5_DIR=C:/Qt/%QTVER%/%QTCOMPILER%/lib/cmake/Qt5 -DBOOST_ROOT=C:/Libraries/boost_1_69_0 -DCMAKE_BUILD_TYPE=Release -DLSL_INSTALL_ROOT=LSL/ %CMakeArgs%
- sh: cmake -S . -B build -DLSL_INSTALL_ROOT=LSL/usr -DLSL_UNIXFOLDERS=1 -DCMAKE_BUILD_TYPE=Release ${CMakeArgs}
- cd build
- cmake --build . --config Release --target install
- cpack
artifacts:
- path: 'build/*.deb'
- path: 'build/*.tar.*'
- path: 'build/*.7z'
deploy:
  provider: GitHub
  auth_token:
    secure: XzGnVTRjZI2AuQzR5A6qPgZViAAbBVq7/VhM7O8kyTmjIkvUjH1RrwWiFLuinsus
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true
