language: cpp
compiler: clang
env:
  LSL_VERSION="1.13.0-b13"
matrix:
  include:
  - os: osx
    osx_image: xcode10.1
before_install:
- mkdir LSL
- brew update
- brew upgrade cmake
install:
- git clone https://github.com/sccn/liblsl.git
- mkdir liblsl/build && cd liblsl/build
- cmake -DCMAKE_INSTALL_PREFIX=../../LSL/ -DLSL_UNIXFOLDERS=ON ..
- cmake --build . --config Release --target install
- cd ../..
before_script:
- brew install qt;
- export LSL_INSTALL_ROOT=LSL
script:
- mkdir build && cd build
- cmake --version
- cmake -DLSL_INSTALL_ROOT=${LSL_INSTALL_ROOT} -DQt5_DIR=/usr/local/opt/qt/lib/cmake/Qt5 ..
- cmake --build . --config Release --target install
- cd install/Labrecorder
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then for app in *.app; do /usr/local/opt/qt/bin/macdeployqt
  ${app} -dmg; mv "${app%.app}.dmg" "${app%.app}-${LSL_VERSION}-${TRAVIS_OSX_IMAGE}.dmg";
  done; fi
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: FQ+xqPuImk2ie4KeoDrP1u+6TB2qIoLPTk0wr7EEv+7oBfLodExVSyC67TEUVKUVnAYv2E1FFfHLZPUzMeiuFT6o40jkwekHEte3dbgWTgmW9iqiDw4eK5X0obZbDoYLJBbOiQfUsgH8nKpE/U5MprTpQ3KKQr2CjbcqGZnDY6k2yNope70bMe//4zBgv+qjvR1CDeI8sSrSUkBgDgVhujqNzS8I0FPoLAmJuBuFiA5Y7f/uwO17M1Nfso9WnNiWA8XhgJ1mgoA8BYrIx9hP2niK4gkFJ3p/iV0IK51KNxEELIQ7IKw/U12CLYD7+hKFBpyrZGcgCwXCHXR/G3/kNsxJrk395u+78gTLdiE3AuksWQZ+f+6br2pBG3UBTu/Qm3cVcVQRtNArKXDgiCaMc0qECL51o6qNTzPhLAHvGVGZCOjp34vW44MMWtKh584LqShojN/DH1OBUR3PjaHHiuxQMuaUXHto8SDfl0ZRSaeyElI+6kmU3XfTJfqFq2DpTX5LMYoiZUXwMKKQtWTGp8I2axL1LCnUsX/nlY63AoCY7CJTwX+DE1//YBwOsfafQ/VOMIpzQCXJNuHR3EAFVk+qcFt0wTVu/aa2oTkBaGN67LE22/pkwT4kxpI3kaXDo94CE0diEZWu4hHHNoQF1C/WuH/DH4HErJW8tPGrEm8=
  file:
  - LabRecorder-${LSL_VERSION}-${TRAVIS_OSX_IMAGE}.dmg
  - LabRecorderCLI-${LSL_VERSION}-${TRAVIS_OSX_IMAGE}.dmg
  on:
    repo: labstreaminglayer/App-LabRecorder
    tags: true
